version: '3.3'

services:
  cassandra:
    build:
      context: ./cassandra
      dockerfile: Dockerfile
    image: cassandra:3.11.4
    container_name: ttscassandra
    volumes:
      - ./cassandra/data:/var/lib/cassandra   
    ports:
      - 9042:9042
    networks: 
      app_net:
        ipv4_address: 172.100.100.2

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.100.0/24